### ISSUE TITLE
Bluetooth control in car is broken

### ISSUE THREAD

**Issue by GithubGrisen** [ubports/ubports-touch#279]
- Device: Bacon
- Channel: Stable
- Build: 15.04 OTA2 - build number ?

## Steps to reproduce

1. ... Dial number from my car
2. ...
3. ...

## Expected behavoir

... Phone should dial the number

## Actual behavior

... Nothing happens

## Logfiles and additional information

... Which logfiles are relevant?
If I dial on the phone, both speakers and microphone work. It's the control functions that are broken. The car also says unknown number, even though the address book is transferred to the car.
Car is Tesla Model S.

**Comment by GithubGrisen** [comment]
When I think back, I'm pretty sure I saw the same behaviour from OTA8 -> 9 on an E4.5 with the original UT, but on another bluetooth set (Parrot).

**Comment by mariogrip** [comment]
I have pushed the latest version (5.50) of bluez to xenial_-_new-bluez please try this to see if it fixes the issue :)

`sudo ubports-qa install xenial_-_new-bluez`

**Comment by GithubGrisen** [comment]
It gets stuck at configuring. If I try dpkg --reconfigure it stops at bluetooth stop/waiting....
This is on a fresh install of OPO

**Comment by fredldotme** [comment]
> It gets stuck at configuring. If I try dpkg --reconfigure it stops at bluetooth stop/waiting....
> This is on a fresh install of OPO

`apt` getting stuck is expected. You can manually reboot your phone.

**Comment by GithubGrisen** [comment]
Still the same - no sound. Something else has happened though. The car can no longer read the contacts.
bluetoothd -v says 5.50
